name: VGG
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py==2.1.0
  - asttokens==3.0.0
  - astunparse==1.6.3
  - ca-certificates==2024.12.14
  - cachetools==5.5.0
  - certifi==2024.8.30
  - charset-normalizer==3.4.0
  - colorama==0.4.6
  - comm==0.2.2
  - cpython==3.9.20
  - cycler==0.12.1
  - debugpy==1.8.12
  - decorator==5.1.1
  - deepacsa==0.3.1
  - et-xmlfile==2.0.0
  - exceptiongroup==1.2.2
  - executing==2.1.0
  - flatbuffers==1.12
  - fonttools==4.55.2
  - gast==0.4.0
  - google-auth==2.36.0
  - google-auth-oauthlib==0.4.6
  - google-pasta==0.2.0
  - grpcio==1.68.1
  - h5py==3.4.0
  - idna==3.10
  - imageio==2.36.1
  - importlib-metadata==8.5.0
  - ipykernel==6.29.5
  - ipython==8.18.1
  - jedi==0.19.2
  - joblib==1.4.2
  - jupyter_client==8.6.3
  - jupyter_core==5.7.2
  - keras==2.9.0
  - keras-preprocessing==1.1.2
  - keras-unet-collection==0.1.13
  - kiwisolver==1.4.7
  - krb5==1.21.3
  - libclang==18.1.1
  - libsodium==1.0.20
  - markdown==3.7
  - markupsafe==3.0.2
  - matplotlib==3.5.2
  - matplotlib-inline==0.1.7
  - nest-asyncio==1.6.0
  - networkx==3.2.1
  - numpy==1.21.2
  - oauthlib==3.2.2
  - opencv-contrib-python==4.5.3.56
  - openpyxl==3.0.9
  - openssl==3.4.0
  - opt-einsum==3.4.0
  - packaging==24.2
  - pandas==1.3.3
  - parso==0.8.4
  - pickleshare==0.7.5
  - pillow==8.3.2
  - pip==24.2
  - platformdirs==4.3.6
  - prompt-toolkit==3.0.50
  - protobuf==3.19.6
  - psutil==6.1.1
  - pure_eval==0.2.3
  - pyasn1==0.6.1
  - pyasn1-modules==0.4.1
  - pygments==2.19.1
  - pyparsing==3.2.0
  - python==3.9.20
  - python-dateutil==2.9.0.post0
  - python_abi==3.9
  - pytz==2024.2
  - pywavelets==1.4.1
  - pywin32==307
  - pyzmq==26.2.0
  - requests==2.32.3
  - requests-oauthlib==2.0.0
  - rsa==4.9
  - scikit-image==0.18.3
  - scikit-learn==0.24.2
  - scipy==1.10.1
  - setuptools==75.1.0
  - six==1.17.0
  - sqlite==3.45.3
  - stack_data==0.6.3
  - tensorboard==2.9.1
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.1
  - tensorflow==2.9.0
  - tensorflow-estimator==2.9.0
  - tensorflow-io-gcs-filesystem==0.31.0
  - termcolor==2.5.0
  - threadpoolctl==3.5.0
  - tifffile==2024.8.30
  - tornado==6.4.2
  - tqdm==4.62.2
  - traitlets==5.14.3
  - typing_extensions==4.12.2
  - tzdata==2024b
  - ucrt==10.0.22621.0
  - urllib3==2.2.3
  - vc==14.40
  - vc14_runtime==14.42.34433
  - vs2015_runtime==14.42.34433
  - wcwidth==0.2.13
  - werkzeug==3.1.3
  - wheel==0.44.0
  - wrapt==1.17.0
  - zeromq==4.3.5
  - zipp==3.21.0
